### ISSUE TITLE
Uploading GPML file does not work

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/wikipathways-upgrade#2]
When uploading a GPML the following error message is shown:

![image](https://cloud.githubusercontent.com/assets/2158343/18627977/4b66c73a-7e5e-11e6-8b0c-9da665b3502a.png)

**Comment by mkutmon** [comment]
First error: 
http://stackoverflow.com/questions/18509858/deprecated-function-eregi-is-deprecated-in

Use preg_match function instead -> done!

**Comment by mkutmon** [comment]
Second error occurs when a new pathway is added to the watch list of the author. Still trying to figure out why that happens. If I remove this line, the following error is shown:
![image](https://cloud.githubusercontent.com/assets/2158343/18628898/b0c002a0-7e62-11e6-9790-99e6abf667c3.png)

**Comment by mkutmon** [comment]
- [x] Deprecated function is fixed
- [x]  Watch should be fixed:

```
$watchAction = new WatchAction($gpmlArticle);
$watchAction->doWatch($gpmlTitle, $wgUser);
/*$gpmlArticle->doWatch();*/
```

New error - the WikiPage doesn't get a page id assigned - I have no idea how and where that should happen.- any ideas?

```
exception 'MetaTagException' with message 'Page id can't be empty' in /var/www/upgrade27.wikipathways.org/w/wpi/MetaTag.php:38
Stack trace:
#0 /var/www/upgrade27.wikipathways.org/w/wpi/extensions/PrivatePathways/PrivatePathways.php(44): MetaTag->__construct('page_permission...', 0)
#1 /var/www/upgrade27.wikipathways.org/w/wpi/extensions/PrivatePathways/PrivatePathways.php(23): PermissionManager->read()
#2 /var/www/upgrade27.wikipathways.org/w/wpi/extensions/Pathways/Pathway.php(192): PermissionManager->__construct(0)
#3 /var/www/upgrade27.wikipathways.org/w/wpi/extensions/Pathways/PathwayContent.php(191): Pathway->getPermissionManager()
#4 /var/www/upgrade27.wikipathways.org/w/includes/page/WikiPage.php(2102): PathwayContent->getParserOutput(Object(Title), NULL, Object(ParserOptions))
#5 /var/www/upgrade27.wikipathways.org/w/includes/page/WikiPage.php(1637): WikiPage->prepareContentForEdit(Object(PathwayContent), NULL, Object(User), NULL)
#6 /var/www/upgrade27.wikipathways.org/w/includes/page/WikiPage.php(1527): WikiPage->doEditContent(Object(PathwayContent), 'New pathway', 0, false, NULL)
#7 /var/www/upgrade27.wikipathways.org/w/includes/page/Article.php(2138): WikiPage->doEdit('<?xml version="...', 'New pathway', 0, false, NULL)
#8 /var/www/upgrade27.wikipathways.org/w/wpi/extensions/Pathways/Pathway.php(868): Article->doEdit('<?xml version="...', 'New pathway')
#9 /var/www/upgrade27.wikipathways.org/w/wpi/extensions/Pathways/Pathway.php(771): Pathway->updatePathway('<?xml version="...', 'New pathway')
#10 /var/www/upgrade27.wikipathways.org/w/wpi/extensions/CreatePathway/CreatePathway_body.php(113): Pathway::createNewPathway('<?xml version="...')
#11 /var/www/upgrade27.wikipathways.org/w/wpi/extensions/CreatePathway/CreatePathway_body.php(80): CreatePathway->doUpload('1', NULL)
#12 /var/www/upgrade27.wikipathways.org/w/includes/specialpage/SpecialPage.php(479): CreatePathway->execute(NULL)
#13 /var/www/upgrade27.wikipathways.org/w/includes/specialpage/SpecialPageFactory.php(576): SpecialPage->run(NULL)
#14 /var/www/upgrade27.wikipathways.org/w/includes/MediaWiki.php(282): SpecialPageFactory::executePath(Object(Title), Object(RequestContext))
#15 /var/www/upgrade27.wikipathways.org/w/includes/MediaWiki.php(745): MediaWiki->performRequest()
#16 /var/www/upgrade27.wikipathways.org/w/includes/MediaWiki.php(519): MediaWiki->main()
#17 /var/www/upgrade27.wikipathways.org/w/index.php(43): MediaWiki->run()
#18 {main}
```

**Comment by mkutmon** [comment]
I can't figure out why the page id is empty. It must have something to do with the new media wiki version and how Article / WikiPages are created.

**Comment by AlexanderPico** [comment]
Stared at this one for a while... No progress :(

**Comment by ariutta** [comment]
I'm not seeing an obvious solution here either.
