### ISSUE TITLE
"Edit" tab does not work

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/wikipathways-upgrade#4]
When you have the permissions to edit the pathway page directly, there is an error thrown - it works for help pages - so I assume it is pathway page specific.

```
/w/index.php?title=Pathway:WP4&action=edit MWException from line 2436 of /var/www/upgrade27.wikipathways.org/w/includes/EditPage.php: This content model is not supported: pathway

Backtrace:

#0 /var/www/upgrade27.wikipathways.org/w/includes/EditPage.php(1028): EditPage->toEditText(PathwayContent)
#1 /var/www/upgrade27.wikipathways.org/w/includes/EditPage.php(587): EditPage->initialiseForm()
#2 /var/www/upgrade27.wikipathways.org/w/includes/actions/EditAction.php(59): EditPage->edit()
#3 /var/www/upgrade27.wikipathways.org/w/includes/MediaWiki.php(503): EditAction->show()
#4 /var/www/upgrade27.wikipathways.org/w/includes/MediaWiki.php(288): MediaWiki->performAction(Article, Title)
#5 /var/www/upgrade27.wikipathways.org/w/includes/MediaWiki.php(745): MediaWiki->performRequest()
#6 /var/www/upgrade27.wikipathways.org/w/includes/MediaWiki.php(519): MediaWiki->main()
#7 /var/www/upgrade27.wikipathways.org/w/index.php(43): MediaWiki->run()
#8 {main}
```

**Comment by nunogit** [comment]
Fixed problem.

The method supportsDirectEditing in the content handler for Pathway (PathwaysHandler.php) neded to override the default value and return true.

**Comment by nunogit** [comment]
Problem fixed.

The method supportsDirectEditing in the Pathway handler (PathwaysHandler.php) needed to be overridden and return true.
